server:
  port: 8082

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://user-api:8081
  rabbitmq:
    host: todo-rabbitmq
    username: guest
    password: guest
    port: 5672