server:
  port: 8082

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672