server:
  port: 8080
  servlet:
    context-path: /gateway

client:
  auth-server:
    token-url: http://127.0.0.1:8081/oauth2/token
    client-id: todo-client
    secret: secret
    scopes: todo.read,todo.write

springdoc:
  show-login-endpoint: true
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    enabled: true
    disable-swagger-default-url: true
  show-actuator: false