server:
  port: 8080
  servlet:
    context-path: /gateway

client:
  user-api:
    server-url: http://user-api:8081/user
  todo-api:
    server-url: http://todo-api:8082/todo
  group-api:
    server-url: http://group-api:8083/group
  auth-server:
    token-url: http://user-api:8081/oauth2/token
    client-id: todo-client
    secret: secret
    scopes: todo.read,todo.write

springdoc:
  show-login-endpoint: true
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    enabled: true
    disable-swagger-default-url: true
  show-actuator: false