version: '3.8'
services:
  todo-api:
    build: .
    container_name: todo-api
    image: todo-api
    ports:
      - "8082:8082"
    depends_on:
      - todo-rabbitmq
  todo-rabbitmq:
    image: rabbitmq:management
    ports:
      - '5672:5672'
      - '15672:15672'